_color: '#AAAAAA'
_labelTemplates:
  - ''
  - ''
  - '{{state}}{{unit_of_measurement}}'
_states:
  unavailable:
    color: '#FF6F91'
  unknown:
    color: '#FF6F91'
  error:
    color: '#FF6F91'
  # ======================== On-States ======================
  on:
    color: '#ffd484'
  playing:
    color: '#ffd484'
  open:
    color: '#ffd484'
  opening:
    color: '#ffd484'
  home:
    color: '#ffd484'
  locked:
    color: '#ffd484'
  heat:
    color: '#ffd484'
  active:
    color: '#ffd484'
  # =========================================================

switch:
  labelTemplates:
  icon: mdi:toggle-switch-off
  states:
    on:
      icon: mdi:toggle-switch

light:
  labelTemplates:
  icon: mdi:lightbulb
  color: '#888888'
  feedbackLayout: '$B1'
  feedback: |
    {% set defaultBrightness = (255 if state === 'on' else 0) %}
    {% set brightness = attributes.brightness | default(defaultBrightness, true) %}
    {
      "indicator": {{ brightness / 255 * 100 }},
      "value": "{{ (brightness / 255 * 100) | int }}%"
    }
  states:
    unavailable:
      icon: mdi:lightbulb-alert
    on:
      color: '#ffd484'

input_boolean:
  labelTemplates:
  icon: mdi:toggle-switch-off
  states:
    on:
      icon: mdi:toggle-switch

update:
  icon: mdi:package
  states:
    on:
      icon: mdi:package
      color: '#FF8066'

person:
  icon: mdi:account
  states:
    not_home:
      icon: mdi:account-arrow-right

binary_sensor:
  labelTemplates:
  icon: mdi:radiobox-blank
  states:
    on:
      icon: mdi:radiobox-marked
  classes:
    plug:
      icon: mdi:power-plug-off-outline
      states:
        on:
          icon: mdi:power-plug-outline
    window:
      icon: mdi:window-closed-variant
      states:
        on:
          icon: mdi:window-open-variant
    door:
      icon: mdi:door-closed
      states:
        on:
          icon: mdi:door-open
    motion:
      icon: mdi:motion-sensor
      states:
        off:
          icon: mdi:motion-sensor-off

cover:
  icon: mdi:garage
  states:
    open:
      icon: mdi:garage-open
    closing:
      icon: mdi:arrow-down-box
    opening:
      icon: mdi:arrow-up-box

sensor:
  labelTemplates:
    - ''
    - ''
    - >
      {% if state == 'off' %}
        Detected Off
      {% elif state == 'in_use' %}
        Detected Running
      {% elif state == 'program_ended' %}
        Detected Done
      {% else %}
        {{ state }}
      {% endif %}
  states:
    off:
      color: '#888888'
    in_use:
      color: '#44DD88'
    program_ended:
      color: '#FFD700'

weather:
  labelTemplates:
    - ''
    - ''
    - '{{temperature}}{{temperature_unit}}'
    - '{{humidity}}%'
  states:
    clear-night:
      icon: mdi:weather-night
    cloudy:
      icon: mdi:weather-cloudy
    fog:
      icon: mdi:weather-fog
    hail:
      icon: mdi:weather-hail
    lightning:
      icon: mdi:weather-lightning
    lightning-rainy:
      icon: mdi:weather-lightning-rainy
    partlycloudy:
      icon: mdi:weather-partly-cloudy
    pouring:
      icon: mdi:weather-puring
    rainy:
      icon: mdi:weather-rainy
    snowy:
      icon: mdi:weather-snowy
    snowy-rainy:
      icon: mdi:weather-snowy-rainy
    sunny:
      icon: mdi:weather-sunny
    windy:
      icon: mdi:weather-windy
    windy-variant:
      icon: mdi:weather-windy-variant

lock:
  icon: mdi:lock
  states:
    unlocked:
      icon: mdi:lock-open
    locking:
      icon: mdi:lock-clock
    unlocking:
      icon: mdi:lock-clock
    locked:
      icon: mdi:lock
    jammed:
      icon: mdi:lock-open-alert

vacuum:
  icon: mdi:robot-vacuum
  states:
    cleaning:
      color: '#00C9A7'
    returning:
      color: '#F9F871'

lawn_mower:
  icon: mdi:robot-mower
  states:
    mowing:
      color: '#00C9A7'
    paused:
      color: '#F9F871'
    returning:
      color: '#F9F871'
